export const DIRTY_DOZEN = [
  { phrase: "Va te faire foutre", translation: "Go fuck yourself", notes: "Nuclear option. Point of no return." },
  { phrase: "Ferme ta gueule", translation: "Shut your mouth", notes: "Gueule = animal's mouth. Very aggressive." },
  { phrase: "Tu me fais chier", translation: "You're pissing me off", notes: "Literally 'you make me shit'. Everyday rage." },
  { phrase: "Putain de merde", translation: "Fucking hell", notes: "The holy trinity. Stack as needed." },
  { phrase: "Casse-toi", translation: "Piss off / Get lost", notes: "Sarkozy said this on live TV. Classic." },
  { phrase: "Espèce de connard", translation: "You fucking asshole", notes: "Espèce de + any insult = instant escalation." },
  { phrase: "Ta gueule", translation: "Shut up", notes: "Short, violent. No softening available." },
  { phrase: "Quel fils de pute", translation: "What a son of a bitch", notes: "For when connard isn't enough." },
  { phrase: "Je m'en fous complètement", translation: "I couldn't give less of a fuck", notes: "Completement = truly, completely, magnificently." },
  { phrase: "Dégage de là", translation: "Get out of here / Fuck off", notes: "Also works on dogs. Versatile." },
  { phrase: "Bordel de merde", translation: "What a fucking shitshow", notes: "Bordel = brothel. French swearing is poetic." },
  { phrase: "Sale enculé", translation: "Dirty fucker", notes: "The full package. Reserve for emergencies." },
];

export const SWEAR_WORDS: Array<{ word: string; translation: string; severity: 1 | 2 | 3 }> = [
  // Severity 1 = mild (eye roll), 2 = medium (gasp), 3 = nuclear (silence)
  { word: "merde", translation: "shit", severity: 1 },
  { word: "putain", translation: "fuck (general expletive)", severity: 1 },
  { word: "bordel", translation: "fucking mess / brothel", severity: 1 },
  { word: "con", translation: "asshole / idiot", severity: 2 },
  { word: "connard", translation: "asshole (m)", severity: 2 },
  { word: "connasse", translation: "asshole (f)", severity: 2 },
  { word: "salope", translation: "bitch / slut", severity: 2 },
  { word: "enculé", translation: "fucker", severity: 3 },
  { word: "fils de pute", translation: "son of a bitch", severity: 3 },
  { word: "bâtard", translation: "bastard", severity: 2 },
  { word: "salopard", translation: "bastard / scoundrel", severity: 2 },
  { word: "couillon", translation: "fool (southern French)", severity: 1 },
  { word: "crétin", translation: "cretin / idiot", severity: 1 },
  { word: "abruti", translation: "moron", severity: 1 },
  { word: "imbécile", translation: "imbecile", severity: 1 },
  { word: "débile", translation: "moron / dimwit", severity: 1 },
  { word: "demeuré", translation: "dimwit", severity: 1 },
  { word: "andouille", translation: "idiot (literally: sausage)", severity: 1 },
  { word: "gros con", translation: "fat idiot", severity: 2 },
  { word: "pauvre con", translation: "pathetic asshole", severity: 2 },
  { word: "sale con", translation: "dirty asshole", severity: 2 },
  { word: "espèce de", translation: "you [insult] (intensifier)", severity: 1 },
  { word: "foutre", translation: "to fuck", severity: 2 },
  { word: "niquer", translation: "to fuck (street)", severity: 3 },
  { word: "baiser", translation: "to fuck (also: to kiss)", severity: 2 },
  { word: "chier", translation: "to shit", severity: 1 },
  { word: "pisser", translation: "to piss", severity: 1 },
  { word: "chiotte", translation: "shithole / toilet", severity: 1 },
  { word: "merdique", translation: "shitty (adj)", severity: 1 },
  { word: "cul", translation: "ass", severity: 1 },
  { word: "bite", translation: "dick", severity: 2 },
  { word: "couilles", translation: "balls", severity: 2 },
  { word: "branleur", translation: "wanker", severity: 2 },
  { word: "se branler", translation: "to not give a shit", severity: 2 },
  { word: "péter", translation: "to fart", severity: 1 },
  { word: "chiant", translation: "annoying as hell", severity: 1 },
  { word: "faire chier", translation: "to piss someone off", severity: 1 },
  { word: "je m'en fous", translation: "I don't give a fuck", severity: 1 },
  { word: "je m'en branle", translation: "I don't give a shit", severity: 2 },
  { word: "va chier", translation: "go to hell / fuck off", severity: 2 },
  { word: "nul", translation: "useless / crap (mild)", severity: 1 },
  { word: "la ferme", translation: "shut it", severity: 1 },
  { word: "dégage", translation: "get lost", severity: 1 },
  { word: "casse-toi", translation: "piss off", severity: 2 },
  { word: "ta gueule", translation: "shut your mouth", severity: 2 },
  { word: "ferme-la", translation: "shut it", severity: 1 },
  { word: "ordure", translation: "scum / trash", severity: 2 },
  { word: "porc", translation: "pig (insult)", severity: 2 },
  { word: "charlot", translation: "clown / joke (insult)", severity: 1 },
  { word: "baltringue", translation: "loser / nobody (street)", severity: 2 },
];
